apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      containers:
      - name: rocketdex
        image: ghcr.io/justmiroslav/ci-cd_practice:151dc5f
        ports:
        - containerPort: 3000
